<center><h1> Tensor And Variables <h1></center>

- Tensor Basic
- Casting
- Initialization
- Indexing 
- Broadcasting
- Algebraic Operations
- Matrix Operations
- Commonly Used Functions In ML
- RAGGED TENSOR
- SPARSE TENSOR
- STRING TENSOR

- 1-Tensor Are Multi dimensional Array
- 1- An Array is An Ordered arrangement of numbers

In [1]:
pip install tensorflow

  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.7.1
    Uninstalling typing_extensions-4.7.1:
      Successfully uninstalled typing_extensions-4.7.1
Note: you may need to restart the kernel to use updated packages.


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pydantic-core 2.6.1 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
torchvision 0.15.2 requires torch==2.0.1, but you have torch 1.13.1 which is incompatible.


In [2]:
import tensorflow as tf

In [36]:
tensor_zero_d = tf.constant(5)
print(tensor_zero_d)

tf.Tensor(5, shape=(), dtype=int32)


In [4]:
tensor_one_d = tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [5]:
tensor_one_d =tf.constant([2,0,-3,8,90])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [6]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,4,6],
    [5,8,9],
    [9,7,3]
])
print(tensor_two_d)

tf.Tensor(
[[1 2 0]
 [3 4 6]
 [5 8 9]
 [9 7 3]], shape=(4, 3), dtype=int32)


In [7]:
tensor_three_d = tf.constant([
    [[1,2,3],
     [4,5,6]],

      [[9,8,7],
     [6,5,4]],

      [[4,9,3],
     [1,8,6]],

      [[9,2,3],
     [4,5,6]]
])

print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[9 8 7]
  [6 5 4]]

 [[4 9 3]
  [1 8 6]]

 [[9 2 3]
  [4 5 6]]], shape=(4, 2, 3), dtype=int32)


In [8]:
print(tensor_one_d.shape)

(5,)


In [9]:
print(tensor_two_d.shape)

(4, 3)


In [10]:
print(tensor_three_d.shape)

(4, 2, 3)


In [11]:
tensor_one_d = tf.constant([2,0.,-3,8,90],dtype= tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.int16)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int16)


In [12]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [13]:
tensor_string = tf.constant(["hello world","hi"])
print(tensor_string)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


In [14]:
import numpy as np 

In [15]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [16]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int32)


In [17]:
eye_tensor = tf.eye(
    num_rows =5,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)


In [18]:
fill_tensor = tf.fill(
    [4,5],5,  name=None
)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]], shape=(4, 5), dtype=int32)


In [19]:
one_tensor =tf.zeros(
    [3,2],
    dtype=tf.dtypes.int32,
    name=None
)
print(one_tensor)

tf.Tensor(
[[0 0]
 [0 0]
 [0 0]], shape=(3, 2), dtype=int32)


In [20]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [21]:
random_tensor=tf.random.normal(
    [3,2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[-1.0765815  -0.61218697]
 [-0.7525617  -0.13095632]
 [ 0.55956894  0.5209846 ]], shape=(3, 2), dtype=float32)


# Indexing 

In [22]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[1:5+1])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6  2  4  6 66], shape=(5,), dtype=int32)


In [23]:
tf.range(2,5+1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5])>

In [24]:
x_abs = tf.constant([-2.25 , 3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [25]:
tf.abs(tf.constant(-0.2))

<tf.Tensor: shape=(), dtype=float32, numpy=0.2>

In [26]:
# complex number
x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [27]:
x = tf.constant([1.0, -0.5, 3.4, 0.2, 0.0, -2], dtype = tf.float32)
tf.math.acos(x)

<tf.Tensor: shape=(6,), dtype=float32, numpy=
array([0.       , 2.0943952,       nan, 1.3694383, 1.5707964,       nan],
      dtype=float32)>

In [28]:
x = [1, 2, 3, 4, 5]
y = 0
tf.add(x, y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

In [29]:
x = tf.convert_to_tensor([1, 2, 3, 4, 5])
y = tf.convert_to_tensor(1)
x + y

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6])>

In [30]:
x = [1, 2, 3, 4, 5]
y = tf.constant([1, 2, 3, 4, 5])
tf.add(x, y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10])>

In [31]:
x = tf.constant([1, 2], dtype=tf.int8)
y = [2**7 + 1, 2**7 + 2]
tf.add(x, y)

<tf.Tensor: shape=(2,), dtype=int8, numpy=array([-126, -124], dtype=int8)>

In [32]:
x = np.ones(6).reshape(1, 2, 1, 3)
y = np.ones(6).reshape(2, 1, 3, 1)
tf.add(x, y).shape.as_list()

[2, 2, 3, 3]

In [33]:
input = tf.constant([-2.25 + 4.75j, 3.25 + 5.75j], dtype=tf.complex64)
tf.math.angle(input).numpy()

array([2.0131705, 1.056345 ], dtype=float32)