In [1]:
pip install tensorflow

     ---------------------------------------- 0.0/14.8 MB ? eta -:--:--
     - -------------------------------------- 0.4/14.8 MB 8.1 MB/s eta 0:00:02
     -- ------------------------------------- 0.8/14.8 MB 8.1 MB/s eta 0:00:02
     -- ------------------------------------- 0.9/14.8 MB 6.4 MB/s eta 0:00:03
     --- ------------------------------------ 1.1/14.8 MB 6.0 MB/s eta 0:00:03
     --- ------------------------------------ 1.3/14.8 MB 5.5 MB/s eta 0:00:03
     --- ------------------------------------ 1.5/14.8 MB 5.2 MB/s eta 0:00:03
     ---- ----------------------------------- 1.6/14.8 MB 5.0 MB/s eta 0:00:03
     ---- ----------------------------------- 1.8/14.8 MB 4.8 MB/s eta 0:00:03
     ----- ---------------------------------- 2.0/14.8 MB 4.7 MB/s eta 0:00:03
     ----- ---------------------------------- 2.2/14.8 MB 4.7 MB/s eta 0:00:03
     ------ --------------------------------- 2.4/14.8 MB 4.7 MB/s eta 0:00:03
     ------ --------------------------------- 2.5/14.8 MB 4

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\Shubham\\AppData\\Roaming\\Python\\Python310\\site-packages\\~umpy\\.libs\\libopenblas64__v0.3.23-gcc_10_3_0.dll'
Consider using the `--user` option or check the permissions.



In [2]:
import tensorflow as tf

In [3]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_d = tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [5]:
tensor_one_d =tf.constant([2,0,-3,8,90])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [8]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,4,6],
    [5,8,9],
    [9,7,3]
])
print(tensor_two_d)

tf.Tensor(
[[1 2 0]
 [3 4 6]
 [5 8 9]
 [9 7 3]], shape=(4, 3), dtype=int32)


In [11]:
tensor_three_d = tf.constant([
    [[1,2,3],
     [4,5,6]],

      [[9,8,7],
     [6,5,4]],

      [[4,9,3],
     [1,8,6]],

      [[9,2,3],
     [4,5,6]]
])

print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[9 8 7]
  [6 5 4]]

 [[4 9 3]
  [1 8 6]]

 [[9 2 3]
  [4 5 6]]], shape=(4, 2, 3), dtype=int32)


In [12]:
print(tensor_one_d.shape)

(5,)


In [13]:
print(tensor_two_d.shape)

(4, 3)


In [14]:
print(tensor_three_d.shape)

(4, 2, 3)


In [18]:
tensor_one_d = tf.constant([2,0.,-3,8,90],dtype= tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.int16)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int16)


In [19]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [20]:
tensor_string = tf.constant(["hello world","hi"])
print(tensor_string)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


In [21]:
import numpy as np 

In [26]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [25]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int32)


In [37]:
eye_tensor = tf.eye(
    num_rows =5,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)


In [42]:
fill_tensor = tf.fill(
    [4,5],5,  name=None
)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]], shape=(4, 5), dtype=int32)


In [49]:
one_tensor =tf.zeros(
    [3,2],
    dtype=tf.dtypes.int32,
    name=None
)
print(one_tensor)

tf.Tensor(
[[0 0]
 [0 0]
 [0 0]], shape=(3, 2), dtype=int32)


In [50]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [53]:
random_tensor=tf.random.normal(
    [3,2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 0.65395504 -0.50988823]
 [-0.07947452 -1.161627  ]
 [ 0.02175188  0.511494  ]], shape=(3, 2), dtype=float32)


# Indexing 

In [56]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[1:5+1])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6  2  4  6 66], shape=(5,), dtype=int32)


In [58]:
tf.range(2,5+1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5])>

In [59]:
x_abs = tf.constant([-2.25 , 3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [62]:
tf.abs(tf.constant(-0.2))

<tf.Tensor: shape=(), dtype=float32, numpy=0.2>

In [63]:
# complex number
x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [64]:
x = tf.constant([1.0, -0.5, 3.4, 0.2, 0.0, -2], dtype = tf.float32)
tf.math.acos(x)

<tf.Tensor: shape=(6,), dtype=float32, numpy=
array([0.       , 2.0943952,       nan, 1.3694383, 1.5707964,       nan],
      dtype=float32)>

In [67]:
x = [1, 2, 3, 4, 5]
y = 0
tf.add(x, y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

In [68]:
x = tf.convert_to_tensor([1, 2, 3, 4, 5])
y = tf.convert_to_tensor(1)
x + y

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6])>

In [69]:
x = [1, 2, 3, 4, 5]
y = tf.constant([1, 2, 3, 4, 5])
tf.add(x, y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10])>

In [70]:
x = tf.constant([1, 2], dtype=tf.int8)
y = [2**7 + 1, 2**7 + 2]
tf.add(x, y)

<tf.Tensor: shape=(2,), dtype=int8, numpy=array([-126, -124], dtype=int8)>

In [72]:
x = np.ones(6).reshape(1, 2, 1, 3)
y = np.ones(6).reshape(2, 1, 3, 1)
tf.add(x, y).shape.as_list()

[2, 2, 3, 3]

In [73]:
input = tf.constant([-2.25 + 4.75j, 3.25 + 5.75j], dtype=tf.complex64)
tf.math.angle(input).numpy()

array([2.0131705, 1.056345 ], dtype=float32)